version: 2

updates:
  - package-ecosystem: nuget
    directory: "/ep_weather_host"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
